# automatically generated by the FlatBuffers compiler, do not modify

org.apache.arrow.flatbuf.eval(quote


FlatBuffers.@with_kw mutable struct BodyCompression
#=
#  Optional compression for the memory buffers constituting IPC message
#  bodies. Intended for use with RecordBatch but could be used for other
#  message types
=#
#=
#  Compressor library
=#
    codec::CompressionType = 0
#=
#  Indicates the way the record batch body was compressed
=#
    method::BodyCompressionMethod = 0
end
FlatBuffers.@ALIGN(BodyCompression, 1)
FlatBuffers.slot_offsets(::Type{T}) where {T<:BodyCompression} = [
    0x00000004, 0x00000006
]

BodyCompression(buf::AbstractVector{UInt8}) = FlatBuffers.read(BodyCompression, buf)
BodyCompression(io::IO) = FlatBuffers.deserialize(io, BodyCompression)

end)

