# automatically generated by the FlatBuffers compiler, do not modify

org.apache.arrow.flatbuf.eval(quote


mutable struct Bool
end
FlatBuffers.@ALIGN(Bool, 1)

Bool(buf::AbstractVector{UInt8}) = FlatBuffers.read(Bool, buf)
Bool(io::IO) = FlatBuffers.deserialize(io, Bool)

end)

