# automatically generated by the FlatBuffers compiler, do not modify

org.apache.arrow.flatbuf.eval(quote


FlatBuffers.@STRUCT struct Buffer
#=
#  ----------------------------------------------------------------------
#  A Buffer represents a single contiguous memory segment
=#
#=
#  The relative offset into the shared memory page where the bytes for this
#  buffer starts
=#
    offset::Int64
#=
#  The absolute length (in bytes) of the memory buffer. The memory is found
#  from offset (inclusive) to offset + length (non-inclusive). When building
#  messages using the encapsulated IPC message, padding bytes may be written
#  after a buffer, but such padding bytes do not need to be accounted for in
#  the size here.
=#
    length::Int64
end
FlatBuffers.@ALIGN(Buffer, 8)

Buffer(buf::AbstractVector{UInt8}) = FlatBuffers.read(Buffer, buf)
Buffer(io::IO) = FlatBuffers.deserialize(io, Buffer)

end)

