# automatically generated by the FlatBuffers compiler, do not modify

org.apache.arrow.flatbuf.eval(quote

@enum CompressionType::Int8 begin
    CompressionTypeLZ4_FRAME = 0
    CompressionTypeZSTD = 1
end


end)

