# automatically generated by the FlatBuffers compiler, do not modify

org.apache.arrow.flatbuf.eval(quote


FlatBuffers.@with_kw mutable struct Date
#=
#  Date is either a 32-bit or 64-bit type representing elapsed time since UNIX
#  epoch (1970-01-01), stored in either of two units:
# 
#  * Milliseconds (64 bits) indicating UNIX time elapsed since the epoch (no
#    leap seconds), where the values are evenly divisible by 86400000
#  * Days (32 bits) since the UNIX epoch
=#
    unit::DateUnit = 1
end
FlatBuffers.@ALIGN(Date, 1)
FlatBuffers.slot_offsets(::Type{T}) where {T<:Date} = [
    0x00000004
]

Date(buf::AbstractVector{UInt8}) = FlatBuffers.read(Date, buf)
Date(io::IO) = FlatBuffers.deserialize(io, Date)

end)

