# automatically generated by the FlatBuffers compiler, do not modify

org.apache.arrow.flatbuf.eval(quote


FlatBuffers.@with_kw mutable struct Decimal
#=
#  Total number of decimal digits
=#
    precision::Int32 = 0
#=
#  Number of digits after the decimal point "."
=#
    scale::Int32 = 0
end
FlatBuffers.@ALIGN(Decimal, 1)
FlatBuffers.slot_offsets(::Type{T}) where {T<:Decimal} = [
    0x00000004, 0x00000006
]

Decimal(buf::AbstractVector{UInt8}) = FlatBuffers.read(Decimal, buf)
Decimal(io::IO) = FlatBuffers.deserialize(io, Decimal)

end)

