# automatically generated by the FlatBuffers compiler, do not modify

org.apache.arrow.flatbuf.eval(quote

#=
#  ----------------------------------------------------------------------
#  Dictionary encoding metadata
#  Maintained for forwards compatibility, in the future
#  Dictionaries might be explicit maps between integers and values
#  allowing for non-contiguous index values
=#
@enum DictionaryKind::Int16 begin
    DictionaryKindDenseArray = 0
end


end)

