# automatically generated by the FlatBuffers compiler, do not modify

org.apache.arrow.flatbuf.eval(quote


FlatBuffers.@with_kw mutable struct Duration
    unit::TimeUnit = 1
end
FlatBuffers.@ALIGN(Duration, 1)
FlatBuffers.slot_offsets(::Type{T}) where {T<:Duration} = [
    0x00000004
]

Duration(buf::AbstractVector{UInt8}) = FlatBuffers.read(Duration, buf)
Duration(io::IO) = FlatBuffers.deserialize(io, Duration)

end)

