# automatically generated by the FlatBuffers compiler, do not modify

org.apache.arrow.flatbuf.eval(quote

#=
#  ----------------------------------------------------------------------
#  Endianness of the platform producing the data
=#
@enum Endianness::Int16 begin
    EndiannessLittle = 0
    EndiannessBig = 1
end


end)

