# automatically generated by the FlatBuffers compiler, do not modify

org.apache.arrow.flatbuf.eval(quote


FlatBuffers.@with_kw mutable struct FixedSizeList
#=
#  Number of list items per value
=#
    listSize::Int32 = 0
end
FlatBuffers.@ALIGN(FixedSizeList, 1)
FlatBuffers.slot_offsets(::Type{T}) where {T<:FixedSizeList} = [
    0x00000004
]

FixedSizeList(buf::AbstractVector{UInt8}) = FlatBuffers.read(FixedSizeList, buf)
FixedSizeList(io::IO) = FlatBuffers.deserialize(io, FixedSizeList)

end)

