# automatically generated by the FlatBuffers compiler, do not modify

org.apache.arrow.flatbuf.eval(quote


FlatBuffers.@with_kw mutable struct FloatingPoint
    precision::Precision = 0
end
FlatBuffers.@ALIGN(FloatingPoint, 1)
FlatBuffers.slot_offsets(::Type{T}) where {T<:FloatingPoint} = [
    0x00000004
]

FloatingPoint(buf::AbstractVector{UInt8}) = FlatBuffers.read(FloatingPoint, buf)
FloatingPoint(io::IO) = FlatBuffers.deserialize(io, FloatingPoint)

end)

