# automatically generated by the FlatBuffers compiler, do not modify

org.apache.arrow.flatbuf.eval(quote


FlatBuffers.@with_kw mutable struct Footer{A, B, C, D}
#=
#  ----------------------------------------------------------------------
#  Arrow File metadata
# 
=#
    version::MetadataVersion = 0
    schema::Union{A, Nothing} = nothing
    dictionaries::Vector{B} = []
    recordBatches::Vector{C} = []
#=
#  User-defined metadata
=#
    custom_metadata::Vector{D} = []
end
FlatBuffers.@ALIGN(Footer, 1)
FlatBuffers.slot_offsets(::Type{T}) where {T<:Footer} = [
    0x00000004, 0x00000006, 0x00000008, 0x0000000A, 
    0x0000000C
]
FlatBuffers.root_type(::Type{T}) where {T<:Footer} = true

Footer(buf::AbstractVector{UInt8}) = FlatBuffers.read(Footer{Schema, Block, Block, KeyValue}, buf)
Footer(io::IO) = FlatBuffers.deserialize(io, Footer{Schema, Block, Block, KeyValue})

end)

