# automatically generated by the FlatBuffers compiler, do not modify

org.apache.arrow.flatbuf.eval(quote


FlatBuffers.@with_kw mutable struct Int
    bitWidth::Int32 = 0
    is_signed::Bool = false
end
FlatBuffers.@ALIGN(Int, 1)
FlatBuffers.slot_offsets(::Type{T}) where {T<:Int} = [
    0x00000004, 0x00000006
]

Int(buf::AbstractVector{UInt8}) = FlatBuffers.read(Int, buf)
Int(io::IO) = FlatBuffers.deserialize(io, Int)

end)

