# automatically generated by the FlatBuffers compiler, do not modify

org.apache.arrow.flatbuf.eval(quote

@enum IntervalUnit::Int16 begin
    IntervalUnitYEAR_MONTH = 0
    IntervalUnitDAY_TIME = 1
end


end)

