# automatically generated by the FlatBuffers compiler, do not modify

org.apache.arrow.flatbuf.eval(quote


FlatBuffers.@with_kw mutable struct Interval
    unit::IntervalUnit = 0
end
FlatBuffers.@ALIGN(Interval, 1)
FlatBuffers.slot_offsets(::Type{T}) where {T<:Interval} = [
    0x00000004
]

Interval(buf::AbstractVector{UInt8}) = FlatBuffers.read(Interval, buf)
Interval(io::IO) = FlatBuffers.deserialize(io, Interval)

end)

