# automatically generated by the FlatBuffers compiler, do not modify

org.apache.arrow.flatbuf.eval(quote


mutable struct LargeUtf8
#=
#  Same as Utf8, but with 64-bit offsets, allowing to represent
#  extremely large data values.
=#
end
FlatBuffers.@ALIGN(LargeUtf8, 1)

LargeUtf8(buf::AbstractVector{UInt8}) = FlatBuffers.read(LargeUtf8, buf)
LargeUtf8(io::IO) = FlatBuffers.deserialize(io, LargeUtf8)

end)

