# automatically generated by the FlatBuffers compiler, do not modify

org.apache.arrow.flatbuf.eval(quote


mutable struct LargeBinary
#=
#  Same as Binary, but with 64-bit offsets, allowing to represent
#  extremely large data values.
=#
end
FlatBuffers.@ALIGN(LargeBinary, 1)

LargeBinary(buf::AbstractVector{UInt8}) = FlatBuffers.read(LargeBinary, buf)
LargeBinary(io::IO) = FlatBuffers.deserialize(io, LargeBinary)

end)

