# automatically generated by the FlatBuffers compiler, do not modify

org.apache.arrow.flatbuf.eval(quote


mutable struct LargeList
#=
#  Same as List, but with 64-bit offsets, allowing to represent
#  extremely large data values.
=#
end
FlatBuffers.@ALIGN(LargeList, 1)

LargeList(buf::AbstractVector{UInt8}) = FlatBuffers.read(LargeList, buf)
LargeList(io::IO) = FlatBuffers.deserialize(io, LargeList)

end)

