# automatically generated by the FlatBuffers compiler, do not modify

org.apache.arrow.flatbuf.eval(quote


mutable struct List
end
FlatBuffers.@ALIGN(List, 1)

List(buf::AbstractVector{UInt8}) = FlatBuffers.read(List, buf)
List(io::IO) = FlatBuffers.deserialize(io, List)

end)

