# automatically generated by the FlatBuffers compiler, do not modify

org.apache.arrow.flatbuf.eval(quote


struct MessageHeaderSchema end
MessageHeaderSchema(args...; kwargs...) = Schema(args...; kwargs...)

struct MessageHeaderDictionaryBatch end
MessageHeaderDictionaryBatch(args...; kwargs...) = DictionaryBatch(args...; kwargs...)

struct MessageHeaderRecordBatch end
MessageHeaderRecordBatch(args...; kwargs...) = RecordBatch(args...; kwargs...)

struct MessageHeaderTensor end
MessageHeaderTensor(args...; kwargs...) = Tensor(args...; kwargs...)

struct MessageHeaderSparseTensor end
MessageHeaderSparseTensor(args...; kwargs...) = SparseTensor(args...; kwargs...)

FlatBuffers.@UNION(MessageHeader, (
    Nothing,
    MessageHeaderSchema,
    MessageHeaderDictionaryBatch,
    MessageHeaderRecordBatch,
    MessageHeaderTensor,
    MessageHeaderSparseTensor,
))


end)

