# automatically generated by the FlatBuffers compiler, do not modify

org.apache.arrow.flatbuf.eval(quote


FlatBuffers.@with_kw mutable struct Message{A, B}
    version::MetadataVersion = 0
    header_type::UInt8 = 0
    header::A = nothing
    bodyLength::Int64 = 0
    custom_metadata::Vector{B} = []
end
FlatBuffers.@ALIGN(Message, 1)
FlatBuffers.slot_offsets(::Type{T}) where {T<:Message} = [
    0x00000004, 0x00000006, 0x00000008, 0x0000000A, 
    0x0000000C
]
FlatBuffers.root_type(::Type{T}) where {T<:Message} = true

Message(buf::AbstractVector{UInt8}) = FlatBuffers.read(Message{MessageHeader, KeyValue}, buf)
Message(io::IO) = FlatBuffers.deserialize(io, Message{MessageHeader, KeyValue})

end)

