# automatically generated by the FlatBuffers compiler, do not modify

org.apache.arrow.flatbuf.eval(quote

@enum MetadataVersion::Int16 begin
#=
#  0.1.0
=#
    MetadataVersionV1 = 0
#=
#  0.2.0
=#
    MetadataVersionV2 = 1
#=
#  0.3.0 -> 0.7.1
=#
    MetadataVersionV3 = 2
#=
#  >= 0.8.0
=#
    MetadataVersionV4 = 3
end


end)

