# automatically generated by the FlatBuffers compiler, do not modify

org.apache.arrow.flatbuf.eval(quote


mutable struct Null
#=
#  These are stored in the flatbuffer in the Type union below
=#
end
FlatBuffers.@ALIGN(Null, 1)

Null(buf::AbstractVector{UInt8}) = FlatBuffers.read(Null, buf)
Null(io::IO) = FlatBuffers.deserialize(io, Null)

end)

