# automatically generated by the FlatBuffers compiler, do not modify

org.apache.arrow.flatbuf.eval(quote

@enum Precision::Int16 begin
    PrecisionHALF = 0
    PrecisionSINGLE = 1
    PrecisionDOUBLE = 2
end


end)

