# automatically generated by the FlatBuffers compiler, do not modify

org.apache.arrow.flatbuf.eval(quote

@enum SparseMatrixCompressedAxis::Int16 begin
    SparseMatrixCompressedAxisRow = 0
    SparseMatrixCompressedAxisColumn = 1
end


end)

