# automatically generated by the FlatBuffers compiler, do not modify

org.apache.arrow.flatbuf.eval(quote


struct SparseTensorIndexSparseTensorIndexCOO end
SparseTensorIndexSparseTensorIndexCOO(args...; kwargs...) = SparseTensorIndexCOO(args...; kwargs...)

struct SparseTensorIndexSparseMatrixIndexCSX end
SparseTensorIndexSparseMatrixIndexCSX(args...; kwargs...) = SparseMatrixIndexCSX(args...; kwargs...)

struct SparseTensorIndexSparseTensorIndexCSF end
SparseTensorIndexSparseTensorIndexCSF(args...; kwargs...) = SparseTensorIndexCSF(args...; kwargs...)

FlatBuffers.@UNION(SparseTensorIndex, (
    Nothing,
    SparseTensorIndexSparseTensorIndexCOO,
    SparseTensorIndexSparseMatrixIndexCSX,
    SparseTensorIndexSparseTensorIndexCSF,
))


end)

