# automatically generated by the FlatBuffers compiler, do not modify

org.apache.arrow.flatbuf.eval(quote


mutable struct Struct_
#=
#  A Struct_ in the flatbuffer metadata is the same as an Arrow Struct
#  (according to the physical memory layout). We used Struct_ here as
#  Struct is a reserved word in Flatbuffers
=#
end
FlatBuffers.@ALIGN(Struct_, 1)

Struct_(buf::AbstractVector{UInt8}) = FlatBuffers.read(Struct_, buf)
Struct_(io::IO) = FlatBuffers.deserialize(io, Struct_)

end)

