# automatically generated by the FlatBuffers compiler, do not modify

org.apache.arrow.flatbuf.eval(quote

@enum TimeUnit::Int16 begin
    TimeUnitSECOND = 0
    TimeUnitMILLISECOND = 1
    TimeUnitMICROSECOND = 2
    TimeUnitNANOSECOND = 3
end


end)

