# automatically generated by the FlatBuffers compiler, do not modify

org.apache.arrow.flatbuf.eval(quote


struct TypeNull end
TypeNull(args...; kwargs...) = Null(args...; kwargs...)

struct TypeInt end
TypeInt(args...; kwargs...) = Int(args...; kwargs...)

struct TypeFloatingPoint end
TypeFloatingPoint(args...; kwargs...) = FloatingPoint(args...; kwargs...)

struct TypeBinary end
TypeBinary(args...; kwargs...) = Binary(args...; kwargs...)

struct TypeUtf8 end
TypeUtf8(args...; kwargs...) = Utf8(args...; kwargs...)

struct TypeBool end
TypeBool(args...; kwargs...) = Bool(args...; kwargs...)

struct TypeDecimal end
TypeDecimal(args...; kwargs...) = Decimal(args...; kwargs...)

struct TypeDate end
TypeDate(args...; kwargs...) = Date(args...; kwargs...)

struct TypeTime end
TypeTime(args...; kwargs...) = Time(args...; kwargs...)

struct TypeTimestamp end
TypeTimestamp(args...; kwargs...) = Timestamp(args...; kwargs...)

struct TypeInterval end
TypeInterval(args...; kwargs...) = Interval(args...; kwargs...)

struct TypeList end
TypeList(args...; kwargs...) = List(args...; kwargs...)

struct TypeStruct_ end
TypeStruct_(args...; kwargs...) = Struct_(args...; kwargs...)

struct TypeUnion end
TypeUnion(args...; kwargs...) = Union(args...; kwargs...)

struct TypeFixedSizeBinary end
TypeFixedSizeBinary(args...; kwargs...) = FixedSizeBinary(args...; kwargs...)

struct TypeFixedSizeList end
TypeFixedSizeList(args...; kwargs...) = FixedSizeList(args...; kwargs...)

struct TypeMap end
TypeMap(args...; kwargs...) = Map(args...; kwargs...)

struct TypeDuration end
TypeDuration(args...; kwargs...) = Duration(args...; kwargs...)

struct TypeLargeBinary end
TypeLargeBinary(args...; kwargs...) = LargeBinary(args...; kwargs...)

struct TypeLargeUtf8 end
TypeLargeUtf8(args...; kwargs...) = LargeUtf8(args...; kwargs...)

struct TypeLargeList end
TypeLargeList(args...; kwargs...) = LargeList(args...; kwargs...)

FlatBuffers.@UNION(Type, (
    Nothing,
    TypeNull,
    TypeInt,
    TypeFloatingPoint,
    TypeBinary,
    TypeUtf8,
    TypeBool,
    TypeDecimal,
    TypeDate,
    TypeTime,
    TypeTimestamp,
    TypeInterval,
    TypeList,
    TypeStruct_,
    TypeUnion,
    TypeFixedSizeBinary,
    TypeFixedSizeList,
    TypeMap,
    TypeDuration,
    TypeLargeBinary,
    TypeLargeUtf8,
    TypeLargeList,
))


end)

