# automatically generated by the FlatBuffers compiler, do not modify

org.apache.arrow.flatbuf.eval(quote


mutable struct Utf8
#=
#  Unicode with UTF-8 encoding
=#
end
FlatBuffers.@ALIGN(Utf8, 1)

Utf8(buf::AbstractVector{UInt8}) = FlatBuffers.read(Utf8, buf)
Utf8(io::IO) = FlatBuffers.deserialize(io, Utf8)

end)

