# automatically generated by the FlatBuffers compiler, do not modify

if !isdefined(@__MODULE__(), :org) @__MODULE__().eval(:(module org __precompile__(false); import FlatBuffers end)) end
if !isdefined(org, :apache) org.eval(:(module apache __precompile__(false); import FlatBuffers end)) end
if !isdefined(org.apache, :arrow) org.apache.eval(:(module arrow __precompile__(false); import FlatBuffers end)) end
if !isdefined(org.apache.arrow, :flatbuf) org.apache.arrow.eval(:(module flatbuf __precompile__(false); import FlatBuffers end)) end
include("org/apache/arrow/flatbuf/CompressionType.jl")
include("org/apache/arrow/flatbuf/BodyCompressionMethod.jl")
include("org/apache/arrow/flatbuf/FieldNode.jl")
include("org/apache/arrow/flatbuf/BodyCompression.jl")
include("org/apache/arrow/flatbuf/RecordBatch.jl")
include("org/apache/arrow/flatbuf/DictionaryBatch.jl")
include("org/apache/arrow/flatbuf/MessageHeader.jl")
include("org/apache/arrow/flatbuf/Message.jl")
